/**
 * Freeze the two anchor incidents into a fixture: the routes' published stop
 * sequences and polylines, the stops' coordinates, and the production feed
 * rows for the polls in question — nothing reconstructed.
 */
import fs from "node:fs";
import { loadNet } from "./common.js";

const net = loadNet();

const WANT: Array<{ id: string; label: string; routeId: number; bus: string; from: string; to: string }> = [
  { id: "red316", label: "Red", routeId: 3, bus: "#316", from: "2026-09-04T15:36:00Z", to: "2026-09-04T15:47:00Z" },
  { id: "blueWest126", label: "Blue West", routeId: 16, bus: "#126", from: "2026-09-04T01:37:30Z", to: "2026-09-04T01:38:35Z" },
  { id: "blueDay38", label: "Blue Day", routeId: 1, bus: "#38", from: "2026-09-04T15:20:30Z", to: "2026-09-04T15:21:10Z" },
];

const captures = (process.env.CAPTURE ?? "").split(",").filter(Boolean);
const rows: any[] = [];
for (const f of captures) {
  for (const line of fs.readFileSync(f, "utf8").split("\n")) {
    if (!line) continue;
    let r: any; try { r = JSON.parse(line); } catch { continue; }
    rows.push(r);
  }
}

const out: any = {
  note: "Production feed rows, route geometry and stop coordinates for the two anchor incidents. Generated by scripts/.eta-replay/make-incident-fixture.ts; do not hand-edit.",
  routes: {},
  stopCoords: {},
  stopNames: {},
  incidents: {},
};

for (const w of WANT) {
  const stops = net.routeStops[String(w.routeId)]!;
  out.routes[String(w.routeId)] = {
    label: w.label,
    stops,
    path: net.routePaths[String(w.routeId)]!.map(([a, b]) => [Number(a.toFixed(6)), Number(b.toFixed(6))]),
  };
  for (const s of stops) {
    const c = net.stopCoords[s]!;
    out.stopCoords[String(s)] = { lat: c.lat, lon: c.lon };
    out.stopNames[String(s)] = net.stopById.get(s)?.name ?? String(s);
  }
  const from = Date.parse(w.from), to = Date.parse(w.to);
  const polls: any[] = [];
  let prev = "";
  for (const r of rows.filter((r) => r.bus_name === w.bus && r.collected_at >= from && r.collected_at <= to).sort((a, b) => a.collected_at - b.collected_at)) {
    const k = `${r.lat},${r.lon},${r.last_stop_id}`;
    if (k === prev) continue;
    prev = k;
    polls.push({
      et: new Date(r.collected_at).toLocaleTimeString("en-US", { timeZone: "America/New_York", hour12: false }),
      collected_at: r.collected_at,
      lat: r.lat, lon: r.lon, last_stop_id: r.last_stop_id,
    });
  }
  out.incidents[w.id] = { route_id: w.routeId, bus_name: w.bus, polls };
  console.error(`${w.id}: ${polls.length} polls`);
}

fs.writeFileSync(process.env.OUT!, JSON.stringify(out, null, 1) + "\n");
console.error(`wrote ${process.env.OUT} (${fs.statSync(process.env.OUT!).size} bytes)`);
