"""Build a verified, disk-backed research input spool. Synthetic inputs only."""
import datetime as dt
import json
from pathlib import Path
import shutil
import sqlite3
import sys

from capture_input import (RECORDER, SCRIPT_SHA256, bounded_bytes, digest, file_hash, iter_capture,
                           json_record, regular, require)

EPOCH = dt.datetime(1970, 1, 1, tzinfo=dt.timezone.utc)


def micros(value):
    parsed = dt.datetime.fromisoformat(value.replace('Z', '+00:00'))
    require(parsed.utcoffset() == dt.timedelta(0), 'Non-UTC spool clock')
    elapsed = parsed - EPOCH
    return (elapsed.days * 86400 + elapsed.seconds) * 1000000 + elapsed.microseconds


def spool(prefix, seal, output, proofs):
    prefix, output = Path(prefix), Path(output)
    # This explicit marker is generated by our fixture producer. The present
    # entry point is intentionally unavailable for actual recorder directories.
    marker = json_record(bounded_bytes(regular(prefix, 'synthetic-input.json'), 65536))
    require(marker.get('syntheticOnly') is True and marker.get('outcomes') is False, 'Synthetic input marker required')
    require(not output.exists(), 'Spool destination already exists')
    output.mkdir(parents=True)
    (output/'bodies').mkdir()
    manifest = json_record(bounded_bytes(regular(prefix, 'manifest.json'), 1024*1024))
    with regular(prefix, 'records.jsonl').open('rb') as handle:
        first_hash = digest(handle.readline())
    identity = dict(recorderCommit=RECORDER, recorderScriptSha256=SCRIPT_SHA256,
                    base=manifest['base'], startedAt=manifest['startedAt'], firstRecordSha256=first_hash)
    capture_id = digest(json.dumps(identity, sort_keys=True, separators=(',', ':')).encode())
    database = sqlite3.connect(output/'events.sqlite')
    database.executescript('''
        CREATE TABLE events (ordinal INTEGER PRIMARY KEY, sequence INTEGER, kind TEXT,
          at_us INTEGER, safe INTEGER, event_json TEXT);
        CREATE INDEX by_time ON events(kind,at_us,sequence);
        CREATE TABLE releases (id TEXT PRIMARY KEY, sequence INTEGER, event_json TEXT);
    ''')
    coverage = unsafe = complete = None
    count = 0
    bodies = set()
    try:
        for event in iter_capture(prefix, seal, proofs):
            kind = event['event']
            if kind == 'verification-complete':
                complete = event
                continue
            if kind not in ('release-state', 'fleet-receipt', 'schedule-gap'):
                continue
            if kind == 'schedule-gap':
                event['sequence'] = event['record']['sequence']
                utc = event['record']['at']
            else:
                utc = event.get('receivedAtUtc', event.get('observedReceiptUtc'))
            # iter_capture only yields timestamps already parsed as explicit UTC
            # by iter_verified. Missing/malformed UTC is an integrity failure,
            # whereas clockUnsafe is parseable but noncausal wall ordering.
            at = micros(utc)
            safe = not event.get('clockUnsafe', event.get('releaseEvidence', {}).get('status') == 'clock_unsafe')
            if unsafe is None and not safe:
                unsafe = dict(sequence=event['sequence'], lastSafe=coverage, observedUtc=utc)
            # The decoder is sticky too; enforce a permanent frontier here so
            # no later restored-looking timestamp can extend causal coverage.
            safe = safe and unsafe is None
            if safe:
                coverage = dict(sequence=event['sequence'], atUs=at, atUtc=utc)
            if 'id' in event:
                event['id'] = capture_id + ':' + event['id']
            if kind == 'fleet-receipt':
                event.pop('body', None)
                event['releaseStateId'] = capture_id + ':' + event['releaseStateId']
                sha = event['bodySha256']
                if sha not in bodies:
                    shutil.copyfile(regular(prefix, 'blobs/'+sha+'.gz'), output/'bodies'/f'{sha}.gz')
                    bodies.add(sha)
            event.update(captureId=capture_id, originalAtUtc=utc, atUs=at)
            raw = json.dumps(event, separators=(',', ':'), allow_nan=False)
            database.execute('INSERT INTO events VALUES(?,?,?,?,?,?)',
                             (count, event['sequence'], kind, at, int(safe), raw))
            if kind == 'release-state':
                database.execute('INSERT INTO releases VALUES(?,?,?)', (event['id'], event['sequence'], raw))
            count += 1
            if count % 1000 == 0:
                database.commit()
        require(complete is not None, 'Missing verification completion')
        database.commit()
    finally:
        database.close()
    result = dict(schema=1, syntheticOnly=True, outcomes=False, captureId=capture_id,
                  identity=identity, prefixSha256=seal, verification=complete,
                  coverageStart=dict(atUtc=manifest['startedAt'], atUs=micros(manifest['startedAt'])),
                  coverage=coverage, clockUnsafeBoundary=unsafe, events=count,
                  distinctFleetBodies=len(bodies), syntheticGenerator=marker)
    result['databaseSha256'], result['databaseBytes'] = file_hash(output/'events.sqlite')
    # This is the only publication marker. A failed database/decoder/copy has
    # no ready.json and cannot be consumed by a worker.
    raw_ready = (json.dumps(result, indent=2)+'\n').encode()
    (output/'ready.json').write_bytes(raw_ready)
    (output/'ready.sha256').write_text(digest(raw_ready)+'\n')
    return result


if __name__ == '__main__':
    prefix, seal, output, proof = sys.argv[1:]
    print(json.dumps(spool(prefix, seal, output, [json.loads(Path(proof).read_text())])))
